
#FROM kasmweb/core-ubuntu-focal:1.17.0
FROM kasmweb/core-ubuntu-focal:x86_64-1.16.1-rolling-daily
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########
RUN mkdir /opt/itksnap
COPY itksnap-4.4.0-alpha4-20250730-Linux-x86_64.tar.gz /tmp
RUN tar -xvf /tmp/itksnap-4.4.0-alpha4-20250730-Linux-x86_64.tar.gz -C /opt/itksnap --strip-components=1 \
    && rm /tmp/itksnap-4.4.0-alpha4-20250730-Linux-x86_64.tar.gz


# RUN cp /usr/share/applications/sublime_text.desktop $HOME/Desktop/ \
#     && chmod +x $HOME/Desktop/sublime_text.desktop \
#     && chown 1000:1000 $HOME/Desktop/sublime_text.desktop

RUN echo "/usr/bin/desktop_ready && /opt/itksnap/bin/itksnap &" > $STARTUPDIR/custom_startup.sh \
&& chmod +x $STARTUPDIR/custom_startup.sh


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000